name = "Modpack"
author = "Quinn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a18a4322e9c7a32674cd86fe668361fe596afb4aa2e89da91903748c9f7e4abd"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
