name = "Modpack"
author = "Quinn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "770a6431df271e1b46bf8db6adcfc2feb78bc16047c28b14329f4534cbc7dcc6"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
